name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@ab0a9732c6464e5bb81efb82a2103c7d98f0946f
      - uses: DeterminateSystems/magic-nix-cache-action@b8276522d77f21bf19d3574e5bc99186a6c7aa6c

      - name: Shellcheck
        run: nix develop --command shellcheck scripts/*.sh

      - name: Check formatting
        run: nix develop --command cargo fmt --check

      - name: Clippy
        run: nix develop --command cargo clippy -- -D warnings

      - name: Build
        run: nix build -L

      - name: Test
        run: nix develop --command cargo test
